import numpy as np
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
print("Add two Matrices")
print(np.add(arr1,arr2))
print("Subtract two Matrices")
print(np.subtract(arr1,arr2))
print("Multiply two Matrices")
print(np.multiply(arr1,arr2))
print("Divide two Matrices")
print(np.divide(arr1,arr2))
print("Perform matrix Multiplication")
print(np.dot(arr1,arr2))
print("Display the transpose of the matrix")
print(arr1.transpose())
print(arr2.transpose())
print("Sum of diagonal elements of the matrices")
print(np.trace(arr1))
print(np.trace(arr2))