import numpy as np
matrix=np.random.randint(10,size=(2,2))
print("Random generated matrix")
print(matrix)
det=np.linalg.det(matrix)
print("Determinant of the matrix:",det)
inverse=np.linalg.inv(matrix)
print("Inverse of the matrix:\n",inverse)
rank=np.linalg.matrix_rank(matrix)
print("Rank of the matrix:",rank)
EVal,EVect=np.linalg.eig(matrix)
print("Eigen Values:")
print(EVal)
print("Eigen Vector:")
print(EVect)
array_1D=matrix.flatten()
print("Transform Matrix in 1_D array:",array_1D)